version: '3.8'
services:
  websockettestapplication:
    build:
      context: ./
      dockerfile: WebSocketTestApplication/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: ["dotnet", "WebSocketTestApplication.dll"]
