<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>heirowStocks</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SocketJack/SocketJack.csproj" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
    <Content Include="wwwroot/**" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="wwwroot/**"><LogicalName>heirowStocks.%(Filename)%(Extension)</LogicalName></EmbeddedResource>
  </ItemGroup>
  <ItemGroup><Compile Remove="Program.cs" /></ItemGroup>
</Project>
