
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;

namespace SocketJack.Net {

    /// <summary>
    /// Manages live broadcast relay for an <see cref="HttpServer"/>. Handles OBS upload
    /// (PUT/POST) and RTMP publish ingestion, FLV muxing, viewer queue fan-out, byte
    /// recording, and serves an HTML player page. Call <see cref="Register"/> to wire up
    /// the default routes on the underlying server.
    /// </summary>
    public class BroadcastServer {

        private readonly HttpServer _server;
        private readonly MutableTcpServer _mutableServer;

        // Per-user stream keys: streamKey -> username
        private readonly ConcurrentDictionary<string, string> _streamKeys = new ConcurrentDictionary<string, string>(StringComparer.Ordinal);
        private readonly ConcurrentDictionary<string, UserStreamContext> _userStreams = new ConcurrentDictionary<string, UserStreamContext>(StringComparer.OrdinalIgnoreCase);
        private string _activePublisherName = "";
        private static readonly string KeysDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "SocketJack", "Keys");
        private static readonly string KeysFilePath = Path.Combine(KeysDirectory, "streamkeys.txt");
        private readonly object _keysFileLock = new object();

        // OBS upload relay state
        private Guid _uploadConnectionId = Guid.Empty;
        private string _uploadContentType = "application/octet-stream";
        private readonly ConcurrentDictionary<Guid, BlockingCollection<byte[]>> _viewerQueues = new ConcurrentDictionary<Guid, BlockingCollection<byte[]>>();

        // Byte recording state
        private bool _recording;
        private readonly List<byte[]> _recordedBytes = new List<byte[]>();

        // FLV file header: "FLV" version=1 flags=0x05 (audio+video) headerSize=9 + PreviousTagSize0=0
        // Written to each viewer on connect so mpegts.js can identify the stream format.
        private static readonly byte[] FlvHeader = { 0x46, 0x4C, 0x56, 0x01, 0x05, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00 };

        // Cached FLV initialization tags (metadata, video/audio sequence headers)
        // replayed to every new viewer so late joiners can decode the stream.
        private byte[] _cachedMetadataTag;
        private byte[] _cachedVideoHeaderTag;
        private byte[] _cachedAudioHeaderTag;
        private readonly object _headerLock = new object();

        /// <summary>
        /// Maximum number of queued byte-array items per viewer before <see cref="BroadcastToViewers"/>
        /// starts dropping frames. A larger value tolerates slow readers at the cost of memory.
        /// </summary>
        public int ViewerQueueCapacity { get; set; } = 8192 * 2;

        /// <summary>
        /// Size (in bytes) of the per-viewer write buffer used to batch small FLV tags into
        /// larger HTTP chunks. Defaults to 2 MB. Larger values produce fewer, bigger writes
        /// which improves throughput at the expense of latency.
        /// </summary>
        public int ViewerWriteBufferSize { get; set; } = 2 * 1024 * 1024;

        /// <summary>
        /// Gets or sets the stream key required for RTMP publish connections.
        /// Publishers must supply this key to begin streaming. A random 24-character
        /// key is generated by default. Set to <see langword="null"/> or empty to
        /// allow any key.
        /// </summary>
        public string StreamKey { get; set; } = GenerateStreamKey();

        /// <summary>
        /// Generates a cryptographically random stream key of the specified length
        /// using URL-safe alphanumeric characters (A-Z, a-z, 0-9).
        /// </summary>
        public static string GenerateStreamKey(int length = 24) {
            if( System.Diagnostics.Debugger.IsAttached) return "ass";
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            var bytes = new byte[length];
            using (var rng = RandomNumberGenerator.Create()) {
                rng.GetBytes(bytes);
            }
            var result = new char[length];
            for (int i = 0; i < length; i++) {
                result[i] = chars[bytes[i] % chars.Length];
            }
            return new string(result);
        }

        // RTMP stream statistics
        private bool _rtmpActive;
        private string _rtmpApp = "";
        private string _rtmpStreamKey = "";
        private long _rtmpVideoFrames;
        private long _rtmpAudioFrames;
        private long _rtmpDroppedFrames;
        private long _rtmpTotalBytes;
        private long _rtmpBytesSinceLastTick;
        private double _rtmpBitrate;
        private Stopwatch _rtmpLastTickTime = Stopwatch.StartNew();

        /// <summary>Raised when the broadcast server wants to write a log message.</summary>
        public event Action<string> LogOutput;

        /// <summary>
        /// Raised once per second (or whenever the consumer calls <see cref="UpdateStats"/>)
        /// with the latest RTMP statistics snapshot.
        /// </summary>
        public event Action<RtmpStats> StatsUpdated;

        /// <summary>The underlying <see cref="HttpServer"/> this broadcast server is attached to.</summary>
        public HttpServer Server => _server;

        /// <summary>Gets or sets whether incoming bytes are recorded.</summary>
        public bool Recording {
            get => _recording;
            set {
                if (value && !_recording) {
                    lock (_recordedBytes) { _recordedBytes.Clear(); }
                }
                _recording = value;
            }
        }

        /// <summary>Returns a snapshot of the currently recorded byte chunks.</summary>
        public byte[][] GetRecordedBytes() {
            lock (_recordedBytes) { return _recordedBytes.ToArray(); }
        }

        /// <summary>Clears all recorded byte chunks.</summary>
        public void ClearRecording() {
            lock (_recordedBytes) { _recordedBytes.Clear(); }
        }

        /// <summary>Whether an RTMP publish session is currently active.</summary>
        public bool RtmpActive => _rtmpActive;

        /// <summary>Whether any publish source (RTMP or OBS upload) is currently active.</summary>
        public bool IsPublishing {
            get {
                if (_rtmpActive || _uploadConnectionId != Guid.Empty) return true;
                foreach (var ctx in _userStreams.Values)
                    if (ctx.IsPublishing) return true;
                return false;
            }
        }

        /// <summary>The number of viewers currently connected to the stream.</summary>
        public int ViewerCount {
            get {
                int count = _viewerQueues.Count;
                foreach (var ctx in _userStreams.Values)
                    count += ctx.ViewerCount;
                return count;
            }
        }

        /// <summary>
        /// Maps stream keys to usernames for per-user authentication.
        /// Use <see cref="GetOrCreateStreamKey"/> to generate keys.
        /// </summary>
        public ConcurrentDictionary<string, string> StreamKeys => _streamKeys;

        /// <summary>
        /// The username of the currently active publisher, resolved from <see cref="StreamKeys"/>.
        /// Empty when no one is streaming or when the global <see cref="StreamKey"/> was used.
        /// </summary>
        public string ActivePublisherName => _activePublisherName;

        /// <summary>
        /// Returns the existing stream key for the given <paramref name="username"/>,
        /// or creates and stores a new one if none exists.
        /// </summary>
        public string GetOrCreateStreamKey(string username) {
            if (string.IsNullOrEmpty(username)) return null;
            foreach (var kvp in _streamKeys) {
                if (string.Equals(kvp.Value, username, StringComparison.OrdinalIgnoreCase))
                    return kvp.Key;
            }
            var key = GenerateStreamKey();
            _streamKeys[key] = username;
            SaveStreamKeys();
            return key;
        }

        /// <summary>
        /// Returns the <see cref="UserStreamContext"/> for the given <paramref name="username"/>,
        /// creating one if it does not already exist.
        /// </summary>
        public UserStreamContext GetOrCreateUserStream(string username) {
            if (string.IsNullOrEmpty(username)) return null;
            return _userStreams.GetOrAdd(username, u => new UserStreamContext(u, ViewerQueueCapacity));
        }

        /// <summary>Returns <see langword="true"/> if the specified user is currently publishing a stream.</summary>
        public bool IsUserStreaming(string username) {
            return !string.IsNullOrEmpty(username) && _userStreams.TryGetValue(username, out var ctx) && ctx.IsPublishing;
        }

        /// <summary>Returns the usernames of all users who are currently publishing a stream.</summary>
        public List<string> GetActiveStreamers() {
            var list = new List<string>();
            foreach (var kvp in _userStreams) {
                if (kvp.Value.IsPublishing) list.Add(kvp.Key);
            }
            return list;
        }

        /// <summary>Per-user stream contexts keyed by username.</summary>
        public ConcurrentDictionary<string, UserStreamContext> UserStreams => _userStreams;

        /// <summary>The current RTMP app name (empty when idle).</summary>
        public string RtmpApp => _rtmpApp;

        /// <summary>The current RTMP stream key (empty when idle).</summary>
        public string RtmpStreamKey => _rtmpStreamKey;

        /// <summary>
        /// Creates a new <see cref="BroadcastServer"/> attached to the given <paramref name="server"/>.
        /// Call <see cref="Register"/> to set up the default streaming routes.
        /// </summary>
        public BroadcastServer(HttpServer server) {
            _server = server ?? throw new ArgumentNullException(nameof(server));
            _server.OnReceive += OnServerRawReceive;
            LoadStreamKeys();
        }

        /// <summary>
        /// Creates a new <see cref="BroadcastServer"/> attached to a <see cref="MutableTcpServer"/>.
        /// HTTP streaming routes are registered via the server's <see cref="MutableTcpServer.Http"/> handler.
        /// RTMP publish routes are registered on the base <see cref="HttpServer"/> and handled via
        /// <see cref="MutableTcpServer"/>'s built-in RTMP protocol detection.
        /// </summary>
        public BroadcastServer(MutableTcpServer server) {
            _mutableServer = server ?? throw new ArgumentNullException(nameof(server));
            LoadStreamKeys();
        }

        /// <summary>
        /// Registers the default streaming routes on the underlying <see cref="HttpServer"/>:
        /// <list type="bullet">
        ///   <item><c>GET /stream</c> – HTML player page (mpegts.js)</item>
        ///   <item><c>GET /stream/data</c> – raw FLV relay for the player / VLC</item>
        ///   <item><c>PUT /Upload</c> and <c>POST /Upload</c> – OBS upload ingestion</item>
        ///   <item>RTMP wildcard publish route</item>
        /// </list>
        /// </summary>
        public void Register() {
            if (_mutableServer != null) {
                RegisterMutable();
                return;
            }
            // Serve HTML player page at /stream
            _server.Map("GET", "/stream", (conn, req, ct) => {
                return GetStreamPlayerHtml();
            });

            // JSON status endpoint so the player can check if a publisher is active.
            // Return a plain JSON string so browsers can parse it without SocketJack deserialization.
            _server.Map("GET", "/stream/active", (conn, req, ct) => {
                return "{\"active\":" + (IsPublishing ? "true" : "false") +
                       ",\"viewers\":" + ViewerCount +
                       ",\"rtmp\":" + (_rtmpActive ? "true" : "false") +
                       ",\"upload\":" + (_uploadConnectionId != Guid.Empty ? "true" : "false") + "}";
            });

            // Raw binary FLV relay consumed by the player above (or VLC)
            _server.MapStream("GET", "/stream/data", async (conn, req, chunked, ct) => {
                await Task.Run(async () => {
                    chunked.ContentType = "video/x-flv";

                    // Register the viewer queue BEFORE writing the FLV header so that
                    // any data broadcast while the header is in flight is not lost.
                    var viewerQueue = new BlockingCollection<byte[]>(ViewerQueueCapacity);
                    _viewerQueues.TryAdd(conn.ID, viewerQueue);
                    Log("Stream viewer connected: " + conn.EndPoint.ToString());

                    // Send the FLV file header so mpegts.js can identify the format.
                    chunked.Write(FlvHeader, 0, FlvHeader.Length);

                    // Replay cached initialization tags so late-joining viewers can decode.
                    byte[] metaTag, videoTag, audioTag;
                    lock (_headerLock) {
                        metaTag = _cachedMetadataTag;
                        videoTag = _cachedVideoHeaderTag;
                        audioTag = _cachedAudioHeaderTag;
                    }
                    if (metaTag != null) chunked.Write(metaTag, 0, metaTag.Length);
                    if (videoTag != null) chunked.Write(videoTag, 0, videoTag.Length);
                    if (audioTag != null) chunked.Write(audioTag, 0, audioTag.Length);

                    Log("FLV header sent to viewer " + conn.EndPoint.ToString());

                    try {
                        // Re-usable write buffer – batch small FLV tags into larger
                        // writes so the browser receives fewer, bigger chunks.
                        var writeBuf = new byte[ViewerWriteBufferSize];
                        int bufPos = 0;

                        while (conn.Socket != null && conn.Socket.Connected) {
                            byte[] data;
                            if (viewerQueue.TryTake(out data, 100)) {
                                // If this single item exceeds the buffer, flush what
                                // we have then write the large item directly.
                                if (data.Length > writeBuf.Length) {
                                    try {
                                        if (bufPos > 0) {
                                            chunked.Write(writeBuf, 0, bufPos);
                                            bufPos = 0;
                                        }
                                        chunked.Write(data, 0, data.Length);
                                    }
                                    catch { break; }
                                    continue;
                                }

                                // Flush if appending would overflow the buffer.
                                if (bufPos + data.Length > writeBuf.Length) {
                                    try { chunked.Write(writeBuf, 0, bufPos); }
                                    catch { break; }
                                    bufPos = 0;
                                }

                                Buffer.BlockCopy(data, 0, writeBuf, bufPos, data.Length);
                                bufPos += data.Length;

                                // Keep draining as long as more items are ready and
                                // we haven't filled the buffer yet.
                                while (bufPos < writeBuf.Length && viewerQueue.TryTake(out data, 0)) {
                                    if (bufPos + data.Length > writeBuf.Length) {
                                        try { chunked.Write(writeBuf, 0, bufPos); }
                                        catch { break; }
                                        bufPos = 0;
                                    }
                                    if (data.Length > writeBuf.Length) {
                                        try { chunked.Write(data, 0, data.Length); }
                                        catch { break; }
                                        continue;
                                    }
                                    Buffer.BlockCopy(data, 0, writeBuf, bufPos, data.Length);
                                    bufPos += data.Length;
                                }

                                // Flush whatever is accumulated.
                                if (bufPos > 0) {
                                    try { chunked.Write(writeBuf, 0, bufPos); }
                                    catch { break; }
                                    bufPos = 0;
                                }
                            }
                        }
                    }
                    finally {
                        BlockingCollection<byte[]> removed;
                        _viewerQueues.TryRemove(conn.ID, out removed);
                        viewerQueue.Dispose();
                        Log("Stream viewer disconnected.");
                    }

                    await Task.CompletedTask;
                });
            });

            // OBS upload endpoints
            _server.MapUploadStream("PUT", "/Upload", HandleOBSUpload);
            _server.MapUploadStream("POST", "/Upload", HandleOBSUpload);

            // RTMP wildcard publish route
            _server.MapRtmpPublish("*", HandleRtmpPublish);
        }

        private void RegisterMutable() {
            var http = _mutableServer.Http;

            http.Map("GET", "/stream/active", (conn, req, ct) => {
                var user = GetQueryParam(req.QueryString, "user");
                if (!string.IsNullOrEmpty(user)) {
                    bool userActive = IsUserStreaming(user);
                    int userViewers = _userStreams.TryGetValue(user, out var uctx) ? uctx.ViewerCount : 0;
                    string userTitle = (_userStreams.TryGetValue(user, out var uttl) ? (uttl.Title ?? "") : "").Replace("\\", "\\\\").Replace("\"", "\\\"");
                    return "{\"active\":" + (userActive ? "true" : "false") +
                           ",\"viewers\":" + userViewers +
                           ",\"title\":\"" + userTitle + "\"" +
                           ",\"user\":\"" + user.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"}";
                }
                var streamers = GetActiveStreamers();
                var streamerJson = new List<string>();
                foreach (var s in streamers) {
                    var safeS = s.Replace("\\", "\\\\").Replace("\"", "\\\"");
                    int vc = _userStreams.TryGetValue(s, out var sctx) ? sctx.ViewerCount : 0;
                    string ttl = (_userStreams.TryGetValue(s, out var tctx) ? (tctx.Title ?? "") : "").Replace("\\", "\\\\").Replace("\"", "\\\"");
                    streamerJson.Add("{\"username\":\"" + safeS + "\",\"viewers\":" + vc + ",\"title\":\"" + ttl + "\"}");
                }
                return "{\"active\":" + (IsPublishing ? "true" : "false") +
                       ",\"viewers\":" + ViewerCount +
                       ",\"rtmp\":" + (_rtmpActive ? "true" : "false") +
                       ",\"upload\":" + (_uploadConnectionId != Guid.Empty ? "true" : "false") +
                       ",\"streamers\":[" + string.Join(",", streamerJson) + "]}";
            });

            http.MapStream("GET", "/stream/data", async (conn, req, chunked, ct) => {
                await Task.Run(async () => {
                    var user = GetQueryParam(req.QueryString, "user");
                    UserStreamContext ctx = null;
                    ConcurrentDictionary<Guid, BlockingCollection<byte[]>> targetQueues;
                    if (!string.IsNullOrEmpty(user)) {
                        ctx = GetOrCreateUserStream(user);
                        targetQueues = ctx.ViewerQueues;
                    } else {
                        targetQueues = _viewerQueues;
                    }

                    chunked.ContentType = "video/x-flv";
                    var viewerQueue = new BlockingCollection<byte[]>(ViewerQueueCapacity);
                    targetQueues.TryAdd(conn.ID, viewerQueue);
                    Log("Stream viewer connected" + (ctx != null ? " for " + user : "") + ": " + conn.EndPoint.ToString());
                    chunked.Write(FlvHeader, 0, FlvHeader.Length);

                    byte[] metaTag, videoTag, audioTag;
                    if (ctx != null) {
                        lock (ctx.HeaderLock) { metaTag = ctx.CachedMetadataTag; videoTag = ctx.CachedVideoHeaderTag; audioTag = ctx.CachedAudioHeaderTag; }
                    } else {
                        lock (_headerLock) { metaTag = _cachedMetadataTag; videoTag = _cachedVideoHeaderTag; audioTag = _cachedAudioHeaderTag; }
                    }
                    if (metaTag != null) chunked.Write(metaTag, 0, metaTag.Length);
                    if (videoTag != null) chunked.Write(videoTag, 0, videoTag.Length);
                    if (audioTag != null) chunked.Write(audioTag, 0, audioTag.Length);

                    try {
                        var writeBuf = new byte[ViewerWriteBufferSize];
                        int bufPos = 0;
                        while (conn.Socket != null && conn.Socket.Connected) {
                            byte[] data;
                            if (viewerQueue.TryTake(out data, 100)) {
                                if (data.Length > writeBuf.Length) {
                                    try { if (bufPos > 0) { chunked.Write(writeBuf, 0, bufPos); bufPos = 0; } chunked.Write(data, 0, data.Length); } catch { break; }
                                    continue;
                                }
                                if (bufPos + data.Length > writeBuf.Length) { try { chunked.Write(writeBuf, 0, bufPos); } catch { break; } bufPos = 0; }
                                Buffer.BlockCopy(data, 0, writeBuf, bufPos, data.Length); bufPos += data.Length;
                                while (bufPos < writeBuf.Length && viewerQueue.TryTake(out data, 0)) {
                                    if (bufPos + data.Length > writeBuf.Length) { try { chunked.Write(writeBuf, 0, bufPos); } catch { break; } bufPos = 0; }
                                    if (data.Length > writeBuf.Length) { try { chunked.Write(data, 0, data.Length); } catch { break; } continue; }
                                    Buffer.BlockCopy(data, 0, writeBuf, bufPos, data.Length); bufPos += data.Length;
                                }
                                if (bufPos > 0) { try { chunked.Write(writeBuf, 0, bufPos); } catch { break; } bufPos = 0; }
                            }
                        }
                    } finally {
                        BlockingCollection<byte[]> removed;
                        targetQueues.TryRemove(conn.ID, out removed);
                        viewerQueue.Dispose();
                        Log("Stream viewer disconnected" + (ctx != null ? " from " + user : "") + ".");
                    }
                    await Task.CompletedTask;
                });
            });

            http.MapUploadStream("PUT", "/stream/upload", HandleOBSUploadMutable);
            http.MapUploadStream("POST", "/stream/upload", HandleOBSUploadMutable);

            // Register RTMP publish route on the base HttpServer so that
            // MutableTcpServer's RTMP detection can delegate to it.
            _mutableServer.MapRtmpPublish("*", HandleRtmpPublish);
        }

        private void HandleOBSUploadMutable(NetworkConnection conn, HttpRequest req, UploadStream upload, CancellationToken ct) {
            // Resolve per-user stream from stream key query parameter
            var streamKey = GetQueryParam(req.QueryString, "key");
            UserStreamContext userCtx = null;
            string publisher = null;
            if (!string.IsNullOrEmpty(streamKey) && _streamKeys.TryGetValue(streamKey, out var userName) && !string.IsNullOrEmpty(userName)) {
                publisher = userName;
                userCtx = GetOrCreateUserStream(userName);
                userCtx.Publishing = true;
                _activePublisherName = userName;
            }

            _uploadConnectionId = conn.ID;
            if (req.Headers != null && req.Headers.ContainsKey("Content-Type")) {
                _uploadContentType = req.Headers["Content-Type"];
            }
            Log("OBS upload started" + (publisher != null ? " for " + publisher : "") + " from " + conn.EndPoint.ToString());
            try {
                byte[] data = upload.ReadAsync(ct).GetAwaiter().GetResult();
                while (data != null && data.Length > 0) {
                    if (userCtx != null) {
                        userCtx.BroadcastToViewers(data);
                    } else {
                        BroadcastToViewers(data);
                    }
                    data = upload.ReadAsync(ct).GetAwaiter().GetResult();
                }
            } catch (OperationCanceledException) {
            } catch (Exception ex) {
                Log("OBS upload error: " + ex.Message);
            } finally {
                _uploadConnectionId = Guid.Empty;
                if (userCtx != null) {
                    userCtx.Publishing = false;
                    _activePublisherName = "";
                }
                Log("OBS upload ended.");
            }
        }

        /// <summary>
        /// Broadcasts raw data to all connected stream viewers.
        /// </summary>
        public void BroadcastToViewers(byte[] data) {
            foreach (var kvp in _viewerQueues) {
                try {
                    kvp.Value.TryAdd(data);
                } catch {
                    // viewer queue full or disposed
                }
            }
        }

        /// <summary>
        /// Calculates the current RTMP bitrate and returns a statistics snapshot.
        /// Call this periodically (e.g., once per second) from a timer.
        /// </summary>
        public RtmpStats UpdateStats() {
            double bitrate = 0;
            if (_rtmpActive) {
                double elapsed = _rtmpLastTickTime.Elapsed.TotalSeconds;
                if (elapsed > 0) {
                    long bytesSince = Interlocked.Exchange(ref _rtmpBytesSinceLastTick, 0);
                    bitrate = (bytesSince * 8.0) / elapsed / 1000.0; // kbps
                }
                _rtmpLastTickTime = Stopwatch.StartNew();
                _rtmpBitrate = bitrate;
            }

            var stats = new RtmpStats {
                Active = _rtmpActive,
                App = _rtmpApp,
                StreamKey = _rtmpStreamKey,
                VideoFrames = Interlocked.Read(ref _rtmpVideoFrames),
                AudioFrames = Interlocked.Read(ref _rtmpAudioFrames),
                DroppedFrames = Interlocked.Read(ref _rtmpDroppedFrames),
                TotalBytes = Interlocked.Read(ref _rtmpTotalBytes),
                BitrateKbps = _rtmpBitrate
            };

            StatsUpdated?.Invoke(stats);
            return stats;
        }

        #region Internal handlers

        private void OnServerRawReceive(ref IReceivedEventArgs e) {
            if (e == null || e.Connection == null) return;

            byte[] bytes = GetRawBytes(e.Obj);
            if (bytes != null && bytes.Length > 0) {
                if (_recording) {
                    lock (_recordedBytes) { _recordedBytes.Add(bytes); }
                }
            }
        }

        private void HandleOBSUpload(NetworkConnection conn, HttpRequest req, UploadStream upload, CancellationToken ct) {
            _uploadConnectionId = conn.ID;
            if (req.Headers.ContainsKey("Content-Type")) {
                _uploadContentType = req.Headers["Content-Type"];
            }
            
            Log("OBS upload started from " + conn.EndPoint.ToString());

            try {
                byte[] data;
                while (conn.Socket != null && conn.Socket.Connected) {
                    if (upload.TryRead(out data, 250)) {
                        if (data != null && data.Length > 0) {
                            BroadcastToViewers(data);
                        }
                    }
                }
            }
            finally {
                _uploadConnectionId = Guid.Empty;
                Log("OBS upload ended.");
            }
        }

        private async Task HandleRtmpPublish(NetworkConnection conn, string app, string streamKey, UploadStream upload, CancellationToken ct) {
            // Check per-user stream keys first, then fall back to global StreamKey
            string publisher = null;
            if (_streamKeys.TryGetValue(streamKey ?? "", out var userName)) {
                publisher = userName;
            } else if (!string.IsNullOrEmpty(StreamKey) && string.Equals(streamKey, StreamKey, StringComparison.Ordinal)) {
                publisher = "";
            } else {
                Log("RTMP publish rejected: invalid stream key from " + conn.EndPoint.ToString());
                return;
            }
            _activePublisherName = publisher;

            // Get or create per-user stream context
            UserStreamContext userCtx = null;
            if (!string.IsNullOrEmpty(publisher)) {
                userCtx = GetOrCreateUserStream(publisher);
                userCtx.Publishing = true;
            }

            _rtmpActive = true;
            _rtmpApp = app ?? "";
            _rtmpStreamKey = streamKey ?? "";
            Interlocked.Exchange(ref _rtmpVideoFrames, 0);
            Interlocked.Exchange(ref _rtmpAudioFrames, 0);
            Interlocked.Exchange(ref _rtmpDroppedFrames, 0);
            Interlocked.Exchange(ref _rtmpTotalBytes, 0);
            Interlocked.Exchange(ref _rtmpBytesSinceLastTick, 0);
            _rtmpBitrate = 0;
            _rtmpLastTickTime = Stopwatch.StartNew();

            Log("RTMP publishing started: app=" + _rtmpApp + " key=" + _rtmpStreamKey + " from " + conn.EndPoint.ToString());

            try {
                byte[] chunk = await upload.ReadAsync(ct);
                while (chunk != null) {
                    // New chunk format: [typeId:1][timestamp_ms BE:4][payload]
                    if (chunk.Length < 5) {
                        chunk = await upload.ReadAsync(ct);
                        continue;
                    }

                    byte msgType = chunk[0];
                    int timestamp = (chunk[1] << 24) | (chunk[2] << 16) | (chunk[3] << 8) | chunk[4];
                    int payloadLen = chunk.Length - 5;

                    Interlocked.Add(ref _rtmpTotalBytes, payloadLen);
                    Interlocked.Add(ref _rtmpBytesSinceLastTick, payloadLen);

                    switch (msgType) {
                        case 9: // Video
                            Interlocked.Increment(ref _rtmpVideoFrames);
                            break;
                        case 8: // Audio
                            Interlocked.Increment(ref _rtmpAudioFrames);
                            break;
                        case 18: // Metadata
                            break;
                    }

                    // Build FLV tag and broadcast to viewers
                    if (payloadLen > 0) {
                        byte[] flvTag = BuildFlvTag(msgType, timestamp, chunk, 5, payloadLen);

                        // Broadcast to per-user viewers if publishing under a username,
                        // otherwise broadcast to global viewer queues.
                        if (userCtx != null) {
                            userCtx.BroadcastToViewers(flvTag);
                        } else {
                            BroadcastToViewers(flvTag);
                        }

                        // Cache initialization tags for late-joining viewers.
                        if (userCtx != null) {
                            if (msgType == 18) {
                                lock (userCtx.HeaderLock) { userCtx.CachedMetadataTag = flvTag; }
                            } else if (msgType == 9 && payloadLen >= 2 && chunk[6] == 0x00) {
                                lock (userCtx.HeaderLock) { userCtx.CachedVideoHeaderTag = flvTag; }
                            } else if (msgType == 8 && payloadLen >= 2 && chunk[6] == 0x00) {
                                lock (userCtx.HeaderLock) { userCtx.CachedAudioHeaderTag = flvTag; }
                            }
                            // Cache the last video keyframe (not sequence header) for thumbnail extraction.
                            if (msgType == 9 && payloadLen >= 2 && (chunk[5] & 0xF0) == 0x10 && chunk[6] != 0x00) {
                                lock (userCtx.HeaderLock) { userCtx.LastVideoKeyframeTag = flvTag; }
                            }
                        } else {
                            if (msgType == 18) {
                                lock (_headerLock) { _cachedMetadataTag = flvTag; }
                            } else if (msgType == 9 && payloadLen >= 2 && chunk[6] == 0x00) {
                                lock (_headerLock) { _cachedVideoHeaderTag = flvTag; }
                            } else if (msgType == 8 && payloadLen >= 2 && chunk[6] == 0x00) {
                                lock (_headerLock) { _cachedAudioHeaderTag = flvTag; }
                            }
                        }
                    }

                    // Recording (raw payload without FLV framing)
                    if (_recording && payloadLen > 0) {
                        byte[] payload = new byte[payloadLen];
                        Buffer.BlockCopy(chunk, 5, payload, 0, payloadLen);
                        lock (_recordedBytes) { _recordedBytes.Add(payload); }
                    }

                    chunk = await upload.ReadAsync(ct);
                }
            } catch (OperationCanceledException) {
            } catch (Exception ex) {
                Log("RTMP error: " + ex.Message);
            }

            _rtmpActive = false;
            _activePublisherName = "";
            if (userCtx != null) {
                userCtx.Publishing = false;
                lock (userCtx.HeaderLock) {
                    userCtx.CachedMetadataTag = null;
                    userCtx.CachedVideoHeaderTag = null;
                    userCtx.CachedAudioHeaderTag = null;
                    userCtx.LastVideoKeyframeTag = null;
                }
            }
            lock (_headerLock) {
                _cachedMetadataTag = null;
                _cachedVideoHeaderTag = null;
                _cachedAudioHeaderTag = null;
            }
            Log("RTMP publishing stopped. user=" + (publisher ?? "(global)") + " Video=" + _rtmpVideoFrames + " Audio=" + _rtmpAudioFrames +
                " Dropped=" + _rtmpDroppedFrames + " Total=" + FormatBytes(Interlocked.Read(ref _rtmpTotalBytes)));
        }

        #endregion

        #region Static helpers

        /// <summary>
        /// Builds a complete FLV tag (11-byte header + data + 4-byte PreviousTagSize).
        /// </summary>
        public static byte[] BuildFlvTag(byte tagType, int timestampMs, byte[] src, int srcOffset, int dataSize) {
            // FLV tag = 11 header bytes + dataSize payload + 4 bytes PreviousTagSize
            int tagSize = 11 + dataSize + 4;
            byte[] tag = new byte[tagSize];

            // Tag type (8=audio, 9=video, 18=script/metadata)
            tag[0] = tagType;

            // DataSize (3 bytes, big-endian)
            tag[1] = (byte)((dataSize >> 16) & 0xFF);
            tag[2] = (byte)((dataSize >> 8) & 0xFF);
            tag[3] = (byte)(dataSize & 0xFF);

            // Timestamp (3 bytes lower + 1 byte upper extension)
            tag[4] = (byte)((timestampMs >> 16) & 0xFF);
            tag[5] = (byte)((timestampMs >> 8) & 0xFF);
            tag[6] = (byte)(timestampMs & 0xFF);
            tag[7] = (byte)((timestampMs >> 24) & 0xFF); // TimestampExtended

            // StreamID (always 0 for FLV)
            tag[8] = 0;
            tag[9] = 0;
            tag[10] = 0;

            // Copy payload
            Buffer.BlockCopy(src, srcOffset, tag, 11, dataSize);

            // PreviousTagSize = 11 + dataSize
            int prevSize = 11 + dataSize;
            tag[11 + dataSize] = (byte)((prevSize >> 24) & 0xFF);
            tag[11 + dataSize + 1] = (byte)((prevSize >> 16) & 0xFF);
            tag[11 + dataSize + 2] = (byte)((prevSize >> 8) & 0xFF);
            tag[11 + dataSize + 3] = (byte)(prevSize & 0xFF);

            return tag;
        }

        /// <summary>
        /// Formats a byte count into a human-readable string (B, KB, MB, GB).
        /// </summary>
        public static string FormatBytes(long bytes) {
            if (bytes < 1024) return bytes + " B";
            if (bytes < 1024 * 1024) return (bytes / 1024.0).ToString("N1") + " KB";
            if (bytes < 1024L * 1024 * 1024) return (bytes / (1024.0 * 1024.0)).ToString("N1") + " MB";
            return (bytes / (1024.0 * 1024.0 * 1024.0)).ToString("N2") + " GB";
        }

        /// <summary>
        /// Returns the HTML for an in-browser live stream player that uses mpegts.js to play
        /// an FLV stream from <c>/stream/data</c>.
        /// </summary>
        public static string GetStreamPlayerHtml() {
            return "<!DOCTYPE html><html><head><meta charset=\"utf-8\">" +
                   "<title>SocketJack Live Stream</title>" +
                   "<link rel=\"icon\" href=\"/Images/favicon.ico\" type=\"image/x-icon\">" +
                   // Open Graph metadata for Steam chat / Discord / Slack link previews
                   "<meta property=\"og:title\" content=\"SocketJack Live Stream\">" +
                   "<meta property=\"og:description\" content=\"Live video stream powered by SocketJack\">" +
                   "<meta property=\"og:image\" content=\"/Images/wShare.png\">" +
                   "<meta property=\"og:type\" content=\"video.other\">" +
                   "<meta property=\"og:site_name\" content=\"SocketJack\">" +
                   // Twitter Card metadata (also used by many chat clients)
                   "<meta name=\"twitter:card\" content=\"summary_large_image\">" +
                   "<meta name=\"twitter:title\" content=\"SocketJack Live Stream\">" +
                   "<meta name=\"twitter:description\" content=\"Live video stream powered by SocketJack\">" +
                   "<meta name=\"twitter:image\" content=\"/Images/wShare.png\">" +
                   // Theme color used by Steam, Discord, and others for the embed accent
                   "<meta name=\"theme-color\" content=\"#111111\">" +
                   "<style>" +
                   "body{margin:0;background:#111;color:#eee;font-family:Consolas,sans-serif;display:flex;flex-direction:column;align-items:center;padding:20px}" +
                   "video{width:100%;max-width:1280px;max-height:80vh;background:#000;border-radius:4px}" +
                   "#status{margin:12px;font-size:13px;color:#888}" +
                   "a{color:#5af}" +
                   "</style></head><body>" +
                   "<h2>SocketJack Live Stream</h2>" +
                   "<video id=\"v\" controls autoplay muted></video>" +
                   "<div id=\"status\">Loading player...</div>" +
                   "<script src=\"https://cdn.jsdelivr.net/npm/mpegts.js@1.7.3/dist/mpegts.js\"></script>" +
                   "<script>" +
                   "var st=document.getElementById('status');" +
                   "function checkActive(){" +
                   "  fetch('/stream/active').then(function(r){return r.json()}).then(function(j){" +
                   "    if(!j.active) st.textContent='Connected. Waiting for publisher (OBS) to start streaming...';" +
                   "    else if(!playing) st.textContent='Buffering stream...';" +
                   "  }).catch(function(){});" +
                   "}" +
                   "if(typeof mpegts!=='undefined'&&mpegts.isSupported()){" +
                   "var playing=false;" +
                   "var p=mpegts.createPlayer({type:'flv',isLive:true,url:location.origin+'/stream/data'}," +
                   "{enableWorker:true,liveBufferLatencyChasing:true,liveBufferLatencyMaxLatency:1.5,liveBufferLatencyMinRemain:0.3});" +
                   "p.attachMediaElement(document.getElementById('v'));p.load();" +
                   "p.play().catch(function(){});" +
                   "p.on(mpegts.Events.ERROR,function(t,d){" +
                   "  if(!playing) st.textContent='Player error: '+(d?d.msg||d.reason||t:t);" +
                   "});" +
                   "p.on(mpegts.Events.LOADING_COMPLETE,function(){st.textContent='Stream ended.';playing=false;});" +
                   "document.getElementById('v').addEventListener('playing',function(){" +
                   "  playing=true;st.textContent='Playing';" +
                   "});" +
                   "st.textContent='Connecting to stream...';" +
                   "var poll=setInterval(function(){if(playing){clearInterval(poll);return;}checkActive();},3000);" +
                   "setTimeout(function(){if(!playing)checkActive();},2000);" +
                   "}else{st.textContent='MSE not supported. Open in Chrome/Edge, or play directly in VLC: '+location.origin+'/stream/data';}" +
                   "</script></body></html>";
        }

        private static byte[] GetRawBytes(object obj) {
            if (obj == null) return null;
            if (obj is byte[] ba) return ba;
            if (obj is List<byte> lb) return lb.ToArray();
            return null;
        }

        #endregion

        /// <summary>
        /// Loads persisted stream keys from <c>%APPDATA%\SocketJack\Keys\streamkeys.txt</c>.
        /// Each line is in the format <c>key=username</c>.
        /// </summary>
        private void LoadStreamKeys() {
            try {
                if (!File.Exists(KeysFilePath)) return;
                lock (_keysFileLock) {
                    var lines = File.ReadAllLines(KeysFilePath);
                    foreach (var line in lines) {
                        if (string.IsNullOrWhiteSpace(line)) continue;
                        var sep = line.IndexOf('=');
                        if (sep <= 0 || sep >= line.Length - 1) continue;
                        var key = line.Substring(0, sep);
                        var user = line.Substring(sep + 1);
                        _streamKeys[key] = user;
                    }
                }
            } catch { }
        }

        /// <summary>
        /// Persists all current stream keys to <c>%APPDATA%\SocketJack\Keys\streamkeys.txt</c>.
        /// </summary>
        private void SaveStreamKeys() {
            try {
                lock (_keysFileLock) {
                    if (!Directory.Exists(KeysDirectory))
                        Directory.CreateDirectory(KeysDirectory);
                    var lines = new List<string>();
                    foreach (var kvp in _streamKeys) {
                        lines.Add(kvp.Key + "=" + kvp.Value);
                    }
                    File.WriteAllLines(KeysFilePath, lines);
                }
            } catch { }
        }

        private static string GetQueryParam(string queryString, string name) {
            if (string.IsNullOrEmpty(queryString)) return null;
            var qs = queryString.TrimStart('?');
            foreach (var part in qs.Split('&')) {
                var eq = part.IndexOf('=');
                if (eq > 0 && string.Equals(part.Substring(0, eq), name, StringComparison.OrdinalIgnoreCase)) {
                    return Uri.UnescapeDataString(part.Substring(eq + 1));
                }
            }
            return null;
        }

        private void Log(string text) {
            LogOutput?.Invoke(text);
        }

        /// <summary>
        /// Holds per-user stream state: viewer queues, cached FLV headers, and publishing status.
        /// </summary>
        public class UserStreamContext {
            /// <summary>The username this context belongs to.</summary>
            public readonly string Username;
            internal readonly ConcurrentDictionary<Guid, BlockingCollection<byte[]>> ViewerQueues = new ConcurrentDictionary<Guid, BlockingCollection<byte[]>>();
            internal byte[] CachedMetadataTag;

            /// <summary>The cached AVC/HEVC sequence header FLV tag replayed to late-joining viewers.</summary>
            public byte[] CachedVideoHeaderTag;

            internal byte[] CachedAudioHeaderTag;

            /// <summary>The most recent video keyframe FLV tag, used for thumbnail extraction.</summary>
            public byte[] LastVideoKeyframeTag;

            /// <summary>Lock object for synchronizing access to cached header and keyframe tags.</summary>
            public readonly object HeaderLock = new object();

            /// <summary>User-settable stream title displayed in the stream directory.</summary>
            public string Title { get; set; } = "";

            internal volatile bool Publishing;
            private readonly int _queueCapacity;

            internal UserStreamContext(string username, int queueCapacity) {
                Username = username;
                _queueCapacity = queueCapacity;
            }

            /// <summary>Whether this user is currently publishing a stream.</summary>
            public bool IsPublishing => Publishing;

            /// <summary>The number of viewers currently watching this user's stream.</summary>
            public int ViewerCount => ViewerQueues.Count;

            /// <summary>Broadcasts raw data to all viewers of this user's stream.</summary>
            public void BroadcastToViewers(byte[] data) {
                foreach (var kvp in ViewerQueues) {
                    try { kvp.Value.TryAdd(data); } catch { }
                }
            }
        }
    }

    /// <summary>
    /// Payload returned by the <c>/stream/active</c> endpoint with the current broadcast status.
    /// </summary>
    public class MyPayload {
        /// <summary>Whether any publish source (RTMP or OBS upload) is currently active.</summary>
        public bool Active { get; set; }
        /// <summary>The number of viewers currently connected.</summary>
        public int Viewers { get; set; }
        /// <summary>Whether an RTMP publish session is active.</summary>
        public bool Rtmp { get; set; }
        /// <summary>Whether an OBS upload connection is active.</summary>
        public bool Upload { get; set; }
    }

    /// <summary>
    /// Snapshot of RTMP stream statistics returned by <see cref="BroadcastServer.UpdateStats"/>.
    /// </summary>
    public class RtmpStats {
        /// <summary>Whether an RTMP session is currently active.</summary>
        public bool Active { get; set; }
        /// <summary>The RTMP app name.</summary>
        public string App { get; set; } = "";
        /// <summary>The RTMP stream key.</summary>
        public string StreamKey { get; set; } = "";
        /// <summary>Total video frames received.</summary>
        public long VideoFrames { get; set; }
        /// <summary>Total audio frames received.</summary>
        public long AudioFrames { get; set; }
        /// <summary>Total dropped frames.</summary>
        public long DroppedFrames { get; set; }
        /// <summary>Total bytes received.</summary>
        public long TotalBytes { get; set; }
        /// <summary>Current bitrate in kilobits per second.</summary>
        public double BitrateKbps { get; set; }
    }
}
