using SocketJack.Serialization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;

namespace SocketJack.Net {

    /// <summary>
    /// Controls TypeScript client generation for <see cref="HttpServer"/> routes and
    /// SocketJack WebSocket message types.
    /// </summary>
    public sealed class TypeScriptClientOptions {
        /// <summary>Name of the generated client class.</summary>
        public string ClassName { get; set; } = "SocketJackClient";

        /// <summary>Default base URL passed to the generated client constructor.</summary>
        public string BaseUrl { get; set; } = "";

        /// <summary>When true, emit interfaces for resolvable custom types in the server whitelist.</summary>
        public bool IncludeWebSocketTypes { get; set; } = true;
    }

    public partial class HttpServer {
        /// <summary>
        /// Generates a dependency-free TypeScript client for the server's currently mapped HTTP routes.
        /// Typed request bodies become TypeScript aliases, route variables are required method inputs,
        /// and whitelisted SocketJack message classes are emitted as interfaces for WebSocket use.
        /// </summary>
        public string GenerateTypeScriptClient(TypeScriptClientOptions options = null) {
            return TypeScriptClientGenerator.Generate(this, GetMappedRoutes(), options ?? new TypeScriptClientOptions());
        }
    }

    internal static class TypeScriptClientGenerator {
        private sealed class GeneratedRoute {
            public HttpMappedRoute Route;
            public string MethodName;
            public string TypeName;
            public IReadOnlyList<string> PathVariables;
            public string RequestType;
            public string ResponseType;
            public bool HasBody;
        }

        public static string Generate(HttpServer server, IReadOnlyList<HttpMappedRoute> routes, TypeScriptClientOptions options) {
            string className = TypeScriptIdentifier(options.ClassName, "SocketJackClient", pascalCase: true);
            var generatedRoutes = BuildRoutes(routes ?? Array.Empty<HttpMappedRoute>());
            var output = new StringBuilder(8192);

            output.AppendLine("/* Generated by SocketJack. Changes to this file will be overwritten. */");
            output.AppendLine("/* eslint-disable */");
            output.AppendLine();
            output.AppendLine("export type SocketJackQueryValue = string | number | boolean | null | undefined;");
            output.AppendLine("export interface SocketJackRequestOptions {");
            output.AppendLine("  query?: Record<string, SocketJackQueryValue | readonly SocketJackQueryValue[]>;");
            output.AppendLine("  headers?: Record<string, string>;");
            output.AppendLine("  signal?: AbortSignal;");
            output.AppendLine("}");
            output.AppendLine();
            output.AppendLine("export interface SocketJackClientOptions {");
            output.AppendLine("  baseUrl?: string;");
            output.AppendLine("  fetch?: typeof globalThis.fetch;");
            output.AppendLine("  headers?: Record<string, string>;");
            output.AppendLine("}");
            output.AppendLine();
            output.AppendLine("export interface SocketJackEnvelope<T = unknown> {");
            output.AppendLine("  Type: string;");
            output.AppendLine("  value: T;");
            output.AppendLine("}");
            output.AppendLine();
            output.AppendLine("export class SocketJackHttpError extends Error {");
            output.AppendLine("  constructor(public readonly status: number, public readonly body: unknown, message?: string) {");
            output.AppendLine("    super(message ?? `SocketJack request failed with HTTP ${status}`);");
            output.AppendLine("    this.name = 'SocketJackHttpError';");
            output.AppendLine("  }");
            output.AppendLine("}");

            foreach (var route in generatedRoutes) {
                output.AppendLine();
                output.Append("export type ").Append(route.TypeName).Append("Request = ")
                    .Append(route.RequestType).AppendLine(";");
                output.Append("export type ").Append(route.TypeName).Append("Response = ")
                    .Append(route.ResponseType).AppendLine(";");
            }

            if (options.IncludeWebSocketTypes)
                WriteWebSocketTypes(output, server?.Options?.Whitelist);

            output.AppendLine();
            output.Append("export class ").Append(className).AppendLine(" {");
            output.AppendLine("  private readonly baseUrl: string;");
            output.AppendLine("  private readonly fetchImpl: typeof globalThis.fetch;");
            output.AppendLine("  private readonly defaultHeaders: Record<string, string>;");
            output.AppendLine();
            output.AppendLine("  constructor(options: SocketJackClientOptions = {}) {");
            output.Append("    this.baseUrl = (options.baseUrl ?? ").Append(JsonString(options.BaseUrl ?? "")).AppendLine(").replace(/\\/$/, '');");
            output.AppendLine("    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis);");
            output.AppendLine("    this.defaultHeaders = { ...options.headers };");
            output.AppendLine("  }");

            foreach (var route in generatedRoutes)
                WriteRouteMethod(output, route);

            output.AppendLine();
            output.AppendLine("  connectWebSocket(path = '/', protocols?: string | string[]): WebSocket {");
            output.AppendLine("    const httpUrl = new URL(path, this.baseUrl || globalThis.location?.href || 'http://127.0.0.1');");
            output.AppendLine("    httpUrl.protocol = httpUrl.protocol === 'https:' ? 'wss:' : 'ws:';");
            output.AppendLine("    return protocols === undefined ? new WebSocket(httpUrl) : new WebSocket(httpUrl, protocols);");
            output.AppendLine("  }");
            output.AppendLine();
            output.AppendLine("  sendWebSocket<T>(socket: WebSocket, type: string, value: T): void {");
            output.AppendLine("    const envelope: SocketJackEnvelope<T> = { Type: type, value };");
            output.AppendLine("    socket.send(JSON.stringify(envelope));");
            output.AppendLine("  }");
            output.AppendLine();
            output.AppendLine("  parseWebSocket<T = unknown>(event: MessageEvent<string>): SocketJackEnvelope<T> {");
            output.AppendLine("    return JSON.parse(event.data) as SocketJackEnvelope<T>;");
            output.AppendLine("  }");
            output.AppendLine();
            output.AppendLine("  private resolvePath(template: string, values: Record<string, string | number> = {}): string {");
            output.AppendLine("    let wildcard = 0;");
            output.AppendLine("    return template.replace(/\\{([^}]+)\\}|:([A-Za-z_][A-Za-z0-9_]*)|\\*/g, (_match, braced, colon) => {");
            output.AppendLine("      const name = String(braced ?? colon ?? `path${++wildcard}`);");
            output.AppendLine("      const value = values[name];");
            output.AppendLine("      if (value === undefined || value === null) throw new Error(`Missing route value: ${name}`);");
            output.AppendLine("      return encodeURIComponent(String(value));");
            output.AppendLine("    });");
            output.AppendLine("  }");
            output.AppendLine();
            output.AppendLine("  private async request<T>(method: string, path: string, body: unknown, options: SocketJackRequestOptions, bodyKind: string): Promise<T> {");
            output.AppendLine("    const url = new URL(path, this.baseUrl || globalThis.location?.href || 'http://127.0.0.1');");
            output.AppendLine("    for (const [name, raw] of Object.entries(options.query ?? {})) {");
            output.AppendLine("      const values = Array.isArray(raw) ? raw : [raw];");
            output.AppendLine("      for (const value of values) if (value !== undefined && value !== null) url.searchParams.append(name, String(value));");
            output.AppendLine("    }");
            output.AppendLine("    const headers: Record<string, string> = { Accept: 'application/json', ...this.defaultHeaders, ...options.headers };");
            output.AppendLine("    let requestBody: BodyInit | undefined;");
            output.AppendLine("    if (body !== undefined && body !== null) {");
            output.AppendLine("      if (bodyKind === 'binary' || body instanceof Blob || body instanceof ArrayBuffer || body instanceof FormData) requestBody = body as BodyInit;");
            output.AppendLine("      else if (bodyKind === 'string' || typeof body === 'string') { headers['Content-Type'] ??= 'text/plain; charset=utf-8'; requestBody = String(body); }");
            output.AppendLine("      else { headers['Content-Type'] ??= 'application/json'; requestBody = JSON.stringify(body); }");
            output.AppendLine("    }");
            output.AppendLine("    const response = await this.fetchImpl(url, { method, headers, body: requestBody, signal: options.signal });");
            output.AppendLine("    const contentType = response.headers.get('content-type') ?? '';");
            output.AppendLine("    const responseBody: unknown = response.status === 204 ? undefined : contentType.includes('json') ? await response.json() : await response.text();");
            output.AppendLine("    if (!response.ok) throw new SocketJackHttpError(response.status, responseBody);");
            output.AppendLine("    return responseBody as T;");
            output.AppendLine("  }");
            output.AppendLine("}");
            return output.ToString();
        }

        private static List<GeneratedRoute> BuildRoutes(IReadOnlyList<HttpMappedRoute> routes) {
            var result = new List<GeneratedRoute>();
            var usedNames = new Dictionary<string, int>(StringComparer.Ordinal);
            foreach (var route in routes) {
                if (route == null || string.IsNullOrWhiteSpace(route.Path))
                    continue;
                string baseName = BuildRouteMethodName(route);
                if (usedNames.TryGetValue(baseName, out int count)) {
                    count++;
                    usedNames[baseName] = count;
                    baseName += count.ToString(System.Globalization.CultureInfo.InvariantCulture);
                } else {
                    usedNames[baseName] = 1;
                }
                string typeName = TypeScriptIdentifier(baseName, "Route", pascalCase: true);
                bool hasBody = !string.Equals(route.RequestBodyKind, "none", StringComparison.OrdinalIgnoreCase)
                    && (route.Method == "POST" || route.Method == "PUT" || route.Method == "PATCH" || !string.IsNullOrWhiteSpace(route.RequestBodySchema));
                result.Add(new GeneratedRoute {
                    Route = route,
                    MethodName = TypeScriptIdentifier(baseName, "route", pascalCase: false),
                    TypeName = typeName,
                    PathVariables = InferPathVariables(route.Path).ToList(),
                    RequestType = TypeScriptTypeFromSchema(route.RequestBodySchema, hasBody ? "unknown" : "never"),
                    ResponseType = TypeScriptTypeFromSchema(route.ResponseSchema, "unknown"),
                    HasBody = hasBody
                });
            }
            return result;
        }

        private static void WriteRouteMethod(StringBuilder output, GeneratedRoute route) {
            string requestType = route.TypeName + "Request";
            string responseType = route.TypeName + "Response";
            var parameters = new List<string>();
            if (route.PathVariables.Count > 0)
                parameters.Add("path: { " + string.Join("; ", route.PathVariables.Select(name => TypeScriptProperty(name) + ": string | number")) + " }");
            if (route.HasBody)
                parameters.Add("body: " + requestType);
            parameters.Add("options: SocketJackRequestOptions = {}");
            output.AppendLine();
            output.Append("  async ").Append(route.MethodName).Append('(').Append(string.Join(", ", parameters)).Append("): Promise<")
                .Append(responseType).AppendLine("> {");
            string pathArgument = route.PathVariables.Count > 0 ? "path" : "{}";
            string bodyArgument = route.HasBody ? "body" : "undefined";
            output.Append("    return this.request<").Append(responseType).Append(">(")
                .Append(JsonString(route.Route.Method ?? "GET")).Append(", this.resolvePath(")
                .Append(JsonString(route.Route.Path)).Append(", ").Append(pathArgument).Append("), ")
                .Append(bodyArgument).Append(", options, ").Append(JsonString(route.Route.RequestBodyKind ?? "none")).AppendLine(");");
            output.AppendLine("  }");
        }

        private static void WriteWebSocketTypes(StringBuilder output, TypeList whitelist) {
            if (whitelist == null)
                return;
            var emitted = new HashSet<string>(StringComparer.Ordinal);
            var types = whitelist.Select(Wrapper.GetValueType)
                .Where(type => type != null && type.IsClass && !type.IsAbstract && !type.IsGenericType && type != typeof(string) && type != typeof(Wrapper))
                .Distinct()
                .OrderBy(type => type.FullName, StringComparer.Ordinal)
                .ToList();
            var emittedTypes = new HashSet<Type>(types);
            foreach (Type type in types) {
                string name = TypeScriptIdentifier(type.Name, "SocketJackMessage", pascalCase: true);
                if (!emitted.Add(name)) continue;
                output.AppendLine();
                output.Append("export interface ").Append(name).AppendLine(" {");
                foreach (PropertyInfo property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance).Where(property => property.CanRead && property.GetIndexParameters().Length == 0))
                    output.Append("  ").Append(TypeScriptProperty(property.Name)).Append(": ").Append(TypeScriptTypeFromClr(property.PropertyType, 0, emittedTypes)).AppendLine(";");
                foreach (FieldInfo field in type.GetFields(BindingFlags.Public | BindingFlags.Instance))
                    output.Append("  ").Append(TypeScriptProperty(field.Name)).Append(": ").Append(TypeScriptTypeFromClr(field.FieldType, 0, emittedTypes)).AppendLine(";");
                output.AppendLine("}");
            }
        }

        private static string BuildRouteMethodName(HttpMappedRoute route) {
            string method = (route.Method ?? "GET").ToLowerInvariant();
            var words = new List<string> { method };
            foreach (string segment in (route.Path ?? "").Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries)) {
                string cleaned = segment.Trim('{', '}', '<', '>', '*').TrimStart(':');
                if (!string.IsNullOrWhiteSpace(cleaned))
                    words.Add(cleaned);
            }
            return TypeScriptIdentifier(string.Join(" ", words), method + "Route", pascalCase: false);
        }

        private static IEnumerable<string> InferPathVariables(string path) {
            int wildcard = 0;
            foreach (string segment in (path ?? "").Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries)) {
                string name = null;
                if (segment == "*") name = "path" + (++wildcard);
                else if (segment.StartsWith("{", StringComparison.Ordinal) && segment.EndsWith("}", StringComparison.Ordinal)) name = segment.Substring(1, segment.Length - 2);
                else if (segment.StartsWith(":", StringComparison.Ordinal)) name = segment.Substring(1);
                else if (segment.StartsWith("<", StringComparison.Ordinal) && segment.EndsWith(">", StringComparison.Ordinal)) name = segment.Substring(1, segment.Length - 2);
                if (!string.IsNullOrWhiteSpace(name))
                    yield return TypeScriptIdentifier(name, "path" + Math.Max(1, wildcard), pascalCase: false);
            }
        }

        private static string TypeScriptTypeFromSchema(string schema, string fallback) {
            if (string.IsNullOrWhiteSpace(schema))
                return fallback;
            try {
                using var document = JsonDocument.Parse(schema);
                return TypeScriptTypeFromJson(document.RootElement, 0);
            } catch {
                return fallback;
            }
        }

        private static string TypeScriptTypeFromJson(JsonElement element, int depth) {
            if (depth > 6)
                return "unknown";
            switch (element.ValueKind) {
                case JsonValueKind.String:
                    return TypeScriptPrimitive(element.GetString());
                case JsonValueKind.Array: {
                    var values = element.EnumerateArray().ToList();
                    if (values.Count == 0) return "unknown[]";
                    if (values.Count > 1 && values.All(value => value.ValueKind == JsonValueKind.String))
                        return string.Join(" | ", values.Select(value => JsonString(value.GetString())));
                    return "(" + TypeScriptTypeFromJson(values[0], depth + 1) + ")[]";
                }
                case JsonValueKind.Object: {
                    var properties = element.EnumerateObject().Where(property => property.Name != "$type").ToList();
                    if (properties.Count == 0) return "Record<string, unknown>";
                    return "{ " + string.Join("; ", properties.Select(property => TypeScriptProperty(property.Name) + ": " + TypeScriptTypeFromJson(property.Value, depth + 1))) + " }";
                }
                case JsonValueKind.True:
                case JsonValueKind.False:
                    return "boolean";
                case JsonValueKind.Number:
                    return "number";
                case JsonValueKind.Null:
                case JsonValueKind.Undefined:
                default:
                    return "unknown";
            }
        }

        private static string TypeScriptTypeFromClr(Type type, int depth, ISet<Type> emittedTypes) {
            if (type == null || depth > 4) return "unknown";
            Type nullable = Nullable.GetUnderlyingType(type);
            if (nullable != null) return TypeScriptTypeFromClr(nullable, depth + 1, emittedTypes) + " | null";
            if (type == typeof(object)) return "unknown";
            if (type == typeof(string) || type == typeof(char) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(TimeSpan) || type == typeof(Uri)) return "string";
            if (type == typeof(bool)) return "boolean";
            if (type.IsPrimitive || type == typeof(decimal)) return "number";
            if (type == typeof(byte[])) return "Uint8Array";
            if (type.IsEnum) return string.Join(" | ", Enum.GetNames(type).Select(JsonString));
            if (type.IsArray) return "(" + TypeScriptTypeFromClr(type.GetElementType(), depth + 1, emittedTypes) + ")[]";
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(KeyValuePair<,>)) {
                Type[] arguments = type.GetGenericArguments();
                return "{ Key: " + TypeScriptTypeFromClr(arguments[0], depth + 1, emittedTypes) + "; Value: " + TypeScriptTypeFromClr(arguments[1], depth + 1, emittedTypes) + " }";
            }
            Type dictionary = type.GetInterfaces().Concat(new[] { type }).FirstOrDefault(candidate => candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IDictionary<,>));
            if (dictionary != null) {
                Type[] arguments = dictionary.GetGenericArguments();
                return "Record<string, " + TypeScriptTypeFromClr(arguments[1], depth + 1, emittedTypes) + ">";
            }
            Type enumerable = type.GetInterfaces().Concat(new[] { type }).FirstOrDefault(candidate => candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>));
            if (enumerable != null) return "(" + TypeScriptTypeFromClr(enumerable.GetGenericArguments()[0], depth + 1, emittedTypes) + ")[]";
            if (emittedTypes != null && emittedTypes.Contains(type)) return TypeScriptIdentifier(type.Name, "unknown", pascalCase: true);
            if (type.IsClass || (type.IsValueType && !type.IsPrimitive)) return "Record<string, unknown>";
            return "unknown";
        }

        private static string TypeScriptPrimitive(string value) {
            switch ((value ?? "").Trim().ToLowerInvariant()) {
                case "string":
                case "datetime": return "string";
                case "boolean": return "boolean";
                case "number": return "number";
                case "binary": return "Blob | ArrayBuffer | Uint8Array";
                case "void": return "void";
                case "object":
                case "system.object": return "unknown";
                default: return "unknown";
            }
        }

        private static string TypeScriptProperty(string value) {
            if (!string.IsNullOrWhiteSpace(value)
                && (char.IsLetter(value[0]) || value[0] == '_' || value[0] == '$')
                && value.Skip(1).All(c => char.IsLetterOrDigit(c) || c == '_' || c == '$')
                && !TypeScriptKeywords.Contains(value))
                return value;
            return JsonString(value ?? "value");
        }

        private static string TypeScriptIdentifier(string value, string fallback, bool pascalCase) {
            var words = new List<string>();
            var current = new StringBuilder();
            foreach (char c in value ?? "") {
                if (char.IsLetterOrDigit(c) || c == '_') current.Append(c);
                else if (current.Length > 0) { words.Add(current.ToString()); current.Clear(); }
            }
            if (current.Length > 0) words.Add(current.ToString());
            if (words.Count == 0) words.Add(fallback);
            string first = words[0];
            var result = new StringBuilder();
            if (pascalCase) result.Append(char.ToUpperInvariant(first[0])).Append(first.Substring(1));
            else result.Append(char.ToLowerInvariant(first[0])).Append(first.Substring(1));
            for (int i = 1; i < words.Count; i++)
                result.Append(char.ToUpperInvariant(words[i][0])).Append(words[i].Substring(1));
            if (result.Length == 0) result.Append(fallback);
            if (!char.IsLetter(result[0]) && result[0] != '_' && result[0] != '$') result.Insert(0, '_');
            string identifier = result.ToString();
            return TypeScriptKeywords.Contains(identifier) ? "_" + identifier : identifier;
        }

        private static string JsonString(string value) {
            return JsonSerializer.Serialize(value ?? "");
        }

        private static readonly HashSet<string> TypeScriptKeywords = new HashSet<string>(new[] {
            "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in", "instanceof", "new", "null", "return", "super", "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "as", "implements", "interface", "let", "package", "private", "protected", "public", "static", "yield", "any", "boolean", "constructor", "declare", "get", "module", "require", "number", "set", "string", "symbol", "type", "from", "of"
        }, StringComparer.Ordinal);
    }
}
