# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # or whatever version you're using

      - name: Update .NET workloads
        run: dotnet workload update

      - name: Restore dependencies
        run: dotnet restore

      - name: Build only selected projects
        run: |
          dotnet build ./SocketJack/SocketJack.csproj --configuration Release --no-restore
